data:
  name: KF
  paths: ['/data/NS-Re500_T300_id0-shuffle.npy'] # HPC: ['data/NS-Re500_T300_id0-shuffle.npy']
  Re: 500
  offset: 0
  total_num: 300
  raw_res: [256, 256, 513]
  n_data_samples: 100
  data_res: [64, 64, 257]
  data_high_res_prop: 0.25
  pde_res: [256, 256, 513]
  a_offset: 0
  n_a_samples: 275
  testoffset: 275
  n_test_samples: 25
  t_duration: 0.125
  shuffle: True

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [12, 12, 12, 12]
  modes2: [12, 12, 12, 12]
  modes3: [12, 12, 12, 12]
  fc_dim: 128
  act: gelu
  pad_ratio: [0.0, 0.125]

train:
  batchsize: 1
  start_iter: 0
  num_iter: 100_001
  milestones: [20_000, 60_000, 80_000]
  base_lr: 0.001
  weight_decay: 0.0001
  scheduler_gamma: 0.5
  ic_loss: 0.0
  f_loss: 0.0
  xy_loss: 1.0
  save_step: 5000
  eval_step: 5000

test:
  batchsize: 1
  data_res: [256, 256, 513]

log:
  logdir: Re500-1_8s-800-FNO3D-multiple_input_res-high_res_prop_0_25
  entity: hzzheng-pino
  project: PINO-KF-Re500
  group: Re500-1_8s-800-PINO-s
