data:
  name: KF
  paths: ['data/NS-Re500_T300_id0-shuffle.npy']
  Re: 500
  offset: 0
  total_num: 300
  raw_res: [256, 256, 513]
  n_data_samples: 100
  data_res: [64, 64, 257] # [64, 64, 257]  # resolution in 1 second: training resolution
  pde_res: [64, 64, 257] # [256, 256, 513]   # resolution in 1 second: PDE loss resolution
  a_offset: 0
  n_a_samples: 275
  testoffset: 275
  n_test_samples: 25
  t_duration: 0.125
  shuffle: True

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [12, 12, 12, 12]
  modes2: [12, 12, 12, 12]
  modes3: [12, 12, 12, 12]
  fc_dim: 128
  act: gelu
  pad_ratio: [0.0, 0.125]

train:
  batchsize: 2
  start_iter: 0
  num_iter: 5001 # 200_001
  milestones: [500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500] # [20_000, 60_000, 120_000]
  base_lr: 0.00005 #0.001
  scheduler_gamma: 0.5
  ic_loss: 0.0 #1.0
  f_loss: 0.01 #3.0
  xy_loss: 1.0 #10.0
  save_step: 1000 #5000
  eval_step: 1000 #5000

test:
  batchsize: 1
  data_res: [64, 64, 257] #[256, 256, 513]

log:
  logdir: Re500-1_8s-800-U-F1Net-16m-PINO-f_loss-
  entity: hzzheng-pino
  project: PINO-KF-Re500
  group: Re500-1_8s-800-PINO-s
