data:
  name: KF
  paths: ['/data/NS-Re500_T300_id0-shuffle.npy'] # HPC: ['data/NS-Re500_T300_id0-shuffle.npy']
  Re: 500
  offset: 0
  total_num: 300
  raw_res: [256, 256, 513]
  n_data_samples: 100
  data_res: [64, 64, 257] # [64, 64, 257]  # resolution in 1 second: training resolution
  pde_res: [256, 256, 513] # U-FNet: [64, 64, 257]   # resolution in 1 second: PDE loss resolution
  a_offset: 0
  n_a_samples: 275
  testoffset: 275
  n_test_samples: 25
  t_duration: 0.125
  shuffle: True

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [12, 12, 12, 12]
  modes2: [12, 12, 12, 12]
  modes3: [12, 12, 12, 12]
  fc_dim: 128
  act: gelu
  pad_ratio: [0.0, 0.125]

train:
  batchsize: 2
  start_iter: 0
  num_iter: 200_001 # 5001
  milestones: [20_000, 60_000, 120_000] # [500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500]
  base_lr: 0.001 #0.00005
  weight_decay: 0.0 #0.0001
  scheduler_gamma: 0.5
  ic_loss: 10.0 #0.03
  f_loss: 1.0 #0.1
  xy_loss: 10.0 #1.0
  save_step: 5000 #1000 #5000
  eval_step: 5000 #1000 #5000

test:
  batchsize: 1
  data_res: [256, 256, 513] # U-FNet: [64, 64, 257]

log:
  logdir: Re500-1_8s-800-FNO3D-xy_loss_10-f_loss_1-ic_loss_10
  entity: hzzheng-pino
  project: PINO-KF-Re500
  group: Re500-1_8s-800-PINO-s
